name: lint

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      uses: aminya/setup-cpp@latest
      with:
        clangformat: true

    - name: Run clang-format
      run: |
        find include src -name '*.h' -o -name '*.cc' |  xargs clang-format -i -style=file -fallback-style=none
        git diff --exit-code